//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoRecursosHumanos.Models
{
    using System;
    using System.Collections.Generic;
	using System.ComponentModel.DataAnnotations;

	public partial class empleados
    {
        public int id { get; set; }

		[Display(Name ="Codigo del Empleado")]
        public string codigo_empleado { get; set; }

        public string nombre { get; set; }
        public string apellido { get; set; }
        public string telefono { get; set; }
        public int departamento { get; set; }
        public int cargo { get; set; }

		[Display(Name = "Fecha de Ingreso")]
		public string fecha_ingreso { get; set; }
        public string salario { get; set; }
        public string estatus { get; set; }
    
        public virtual cargos cargos { get; set; }
        public virtual departamentos departamentos { get; set; }
    }
}
