//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoRecursosHumanos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class permisos
    {
        public int id { get; set; }
        public int id_perempleado { get; set; }
        public string desde { get; set; }
        public string hasta { get; set; }
        public string comentarios { get; set; }
    
        public virtual empleados empleados { get; set; }
    }
}
