//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoRecursosHumanos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class salidas
    {
        public int id { get; set; }
        public int id_salempleado { get; set; }
        public string tipo_salida { get; set; }
        public string motivo { get; set; }
        public string fecha_salida { get; set; }
    
        public virtual empleados empleados { get; set; }
    }
}
